// Open Graph/Twitter Card previews (WhatsApp, Slack, Discord, Twitter,
// Facebook, Telegram…) are generated by bots that fetch the raw HTML and
// read <meta> tags from <head> — they never execute JS, so this SPA's
// client-rendered <title>/meta would just show up blank in a shared link's
// preview. Detecting these specific crawlers and serving a small
// server-rendered HTML page (meta tags only, no need to hydrate a real UI)
// is the standard fix short of full SSR. Real search engines (Googlebot,
// Bingbot) do execute JS, but are included too since it costs nothing and
// guarantees a correct <title>/description even if JS execution is skipped
// or fails.
const CRAWLER_USER_AGENT_RE =
  /facebookexternalhit|Facebot|Twitterbot|Slackbot|Discordbot|TelegramBot|WhatsApp|LinkedInBot|Pinterest|redditbot|vkShare|Googlebot|bingbot|Applebot|DuckDuckBot|Yandex|W3C_Validator/i;

export function isCrawlerUserAgent(userAgent) {
  return CRAWLER_USER_AGENT_RE.test(userAgent || '');
}

export function escapeHtml(str) {
  return String(str ?? '').replace(/[&<>"']/g, (ch) => (
    { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]
  ));
}

// video.title/description are user-supplied — everything interpolated
// below is escaped, since this HTML is served directly (not through React,
// which would otherwise auto-escape it for us).
export function renderVideoMetaHtml({ video, pageUrl, imageUrl }) {
  const title = escapeHtml(video.title);
  const description = escapeHtml((video.description || '').slice(0, 200));

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>${title} - StreamBeat</title>
<meta name="description" content="${description}" />
<meta property="og:type" content="video.other" />
<meta property="og:title" content="${title}" />
<meta property="og:description" content="${description}" />
<meta property="og:url" content="${escapeHtml(pageUrl)}" />
${imageUrl ? `<meta property="og:image" content="${escapeHtml(imageUrl)}" />` : ''}
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="${title}" />
<meta name="twitter:description" content="${description}" />
${imageUrl ? `<meta name="twitter:image" content="${escapeHtml(imageUrl)}" />` : ''}
</head>
<body>
<h1>${title}</h1>
<p>${description}</p>
</body>
</html>`;
}
